version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.10.1.1
    ports:
      - "9092:9092"
    volumes:
      - kafkadata:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

volumes:
  kafkadata: